[package]
name = "boa-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boa_engine = { version = "0.16.0", features = ["console"] }
boa_gc = "0.16.0"
gc = "0.4.1"
